### plan_sync.py
"""
Sync approved tasks from .windsurf/plan.md into two repo‑committed artefacts:
  1. docs/roadmap/BACKLOG.yaml   – canonical list of open|in‑progress|done tasks
  2. tasks/<task_id>_<slug>.md   – empty stub created the first time a task appears

Usage (CI):
  python scripts/plan_sync.py --check   # validate no drift
  python scripts/plan_sync.py           # perform update

Assumptions
-----------
* In .windsurf/plan.md, each **approved** task line looks like:
    - [ ] TASK 0007 – Implement canonical serializer   (#open)
    - [x] TASK 0001 – Repo bootstrap                   (#done)
* Phase/epic headers use Markdown H2 / H3 (## / ###), but are ignored here.

This script is intentionally conservative: it never *removes* a task YAML entry,
only adds new ones or flips status once the plan marks them done.
"""
from __future__ import annotations
import argparse, re, sys, yaml, pathlib, textwrap

ROOT = pathlib.Path(__file__).resolve().parents[1]
PLAN_MD = ROOT / '.windsurf' / 'plan.md'
BACKLOG_YML = ROOT / 'docs' / 'roadmap' / 'BACKLOG.yaml'
TASKS_DIR = ROOT / 'tasks'
TASK_PATTERN = re.compile(r"^- \[(?P<mark>[ x])\] TASK (?P<id>\d{4}) – (?P<title>.+)$")


def parse_plan() -> dict[str, str]:
    """Return mapping id -> ('open'|'done', title). Ignores unchecked boxes marked '?'"""
    tasks: dict[str, str] = {}
    if not PLAN_MD.exists():
        return tasks
    for line in PLAN_MD.read_text(encoding='utf8').splitlines():
        m = TASK_PATTERN.match(line.strip())
        if not m:
            continue
        status = 'done' if m['mark'] == 'x' else 'open'
        tasks[m['id']] = {'status': status, 'title': m['title'].strip()}
    return tasks


def load_backlog() -> dict[str, dict]:
    if BACKLOG_YML.exists():
        return yaml.safe_load(BACKLOG_YML.read_text('utf8')) or {}
    return {}


def write_backlog(backlog: dict):
    BACKLOG_YML.parent.mkdir(parents=True, exist_ok=True)
    BACKLOG_YML.write_text(yaml.safe_dump(backlog, sort_keys=True), 'utf8')


def ensure_stub(task_id: str, title: str):
    TASKS_DIR.mkdir(exist_ok=True)
    slug = re.sub(r'[^a-z0-9]+', '_', title.lower()).strip('_')[:40]
    path = TASKS_DIR / f"{task_id}_{slug}.md"
    if not path.exists():
        path.write_text(textwrap.dedent(f"""\
        # TASK {task_id} – {title}

        *This stub was auto‑generated by plan_sync.py.*

        ## Context & Dependencies
        _Fill in after human review_

        ## Technical Requirements
        _TBD_
        """), 'utf8')


def sync(check_only: bool = False) -> bool:
    plan_tasks = parse_plan()
    backlog = load_backlog()
    changed = False
    for tid, meta in plan_tasks.items():
        if tid not in backlog:
            backlog[tid] = meta
            ensure_stub(tid, meta['title'])
            changed = True
        else:
            if backlog[tid]['status'] != meta['status']:
                backlog[tid]['status'] = meta['status']
                changed = True
    if changed and not check_only:
        write_backlog(backlog)
    return changed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='fail if sync would make changes')
    args = ap.parse_args()
    changed = sync(check_only=args.check)
    if args.check and changed:
        print('plan_sync: BACKLOG.yaml or task stubs are out of date', file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
