// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snapshot} from '../models';
import {model} from '../models';

export function CreateSnapshot(arg1:string):Promise<snapshot.Snapshot>;

export function ExecutePlugin(arg1:string,arg2:Record<string, any>):Promise<any>;

export function GetComponentTree():Promise<model.ComponentTree>;

export function GetSnapshots():Promise<Array<snapshot.Snapshot>>;

export function LoadPlugin(arg1:string):Promise<void>;

export function LoadProject(arg1:string):Promise<void>;
