// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnapshot(arg1) {
  return window['go']['main']['App']['CreateSnapshot'](arg1);
}

export function ExecutePlugin(arg1, arg2) {
  return window['go']['main']['App']['ExecutePlugin'](arg1, arg2);
}

export function GetComponentTree() {
  return window['go']['main']['App']['GetComponentTree']();
}

export function GetSnapshots() {
  return window['go']['main']['App']['GetSnapshots']();
}

export function LoadPlugin(arg1) {
  return window['go']['main']['App']['LoadPlugin'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}
