// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {snapshot} from '../models';

export function CreateComponent(arg1:model.Component):Promise<model.Component>;

export function CreateComponentSimple(arg1:string,arg2:string,arg3:string):Promise<model.Component>;

export function CreateProject(arg1:string,arg2:string):Promise<void>;

export function CreateSnapshot(arg1:string):Promise<snapshot.Snapshot>;

export function DeleteComponent(arg1:string):Promise<void>;

export function ExecutePlugin(arg1:string,arg2:Record<string, any>):Promise<any>;

export function GetComponent(arg1:string):Promise<model.Component>;

export function GetComponentTree():Promise<model.ComponentTree>;

export function GetSnapshots():Promise<Array<snapshot.Snapshot>>;

export function InitializeSampleProject():Promise<void>;

export function LoadPlugin(arg1:string):Promise<void>;

export function LoadProject(arg1:string):Promise<void>;

export function UpdateComponent(arg1:string,arg2:model.Component):Promise<model.Component>;
