// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateComponent(arg1) {
  return window['go']['main']['App']['CreateComponent'](arg1);
}

export function CreateComponentSimple(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateComponentSimple'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSnapshot(arg1) {
  return window['go']['main']['App']['CreateSnapshot'](arg1);
}

export function DeleteComponent(arg1) {
  return window['go']['main']['App']['DeleteComponent'](arg1);
}

export function ExecutePlugin(arg1, arg2) {
  return window['go']['main']['App']['ExecutePlugin'](arg1, arg2);
}

export function GetComponent(arg1) {
  return window['go']['main']['App']['GetComponent'](arg1);
}

export function GetComponentTree() {
  return window['go']['main']['App']['GetComponentTree']();
}

export function GetSnapshots() {
  return window['go']['main']['App']['GetSnapshots']();
}

export function InitializeSampleProject() {
  return window['go']['main']['App']['InitializeSampleProject']();
}

export function LoadPlugin(arg1) {
  return window['go']['main']['App']['LoadPlugin'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function UpdateComponent(arg1, arg2) {
  return window['go']['main']['App']['UpdateComponent'](arg1, arg2);
}
