// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog() {
  return window['go']['api']['DialogService']['OpenDirectoryDialog']();
}

export function SetContext(arg1) {
  return window['go']['api']['DialogService']['SetContext'](arg1);
}
