// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Status(arg1) {
  return window['go']['api']['GitService']['Status'](arg1);
}
