// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Rebuild(arg1) {
  return window['go']['api']['IndexService']['Rebuild'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['api']['IndexService']['Search'](arg1, arg2);
}
