// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';

export function Rebuild(arg1:context.Context):Promise<errors.Envelope>;

export function Search(arg1:context.Context,arg2:string):Promise<any|errors.Envelope>;
