// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogHealth(arg1) {
  return window['go']['api']['LoggingService']['GetLogHealth'](arg1);
}

export function GetLogLevels(arg1) {
  return window['go']['api']['LoggingService']['GetLogLevels'](arg1);
}

export function GetLoggingConfig(arg1) {
  return window['go']['api']['LoggingService']['GetLoggingConfig'](arg1);
}

export function GetRecentLogs(arg1, arg2) {
  return window['go']['api']['LoggingService']['GetRecentLogs'](arg1, arg2);
}

export function InitializeProjectLogging(arg1, arg2) {
  return window['go']['api']['LoggingService']['InitializeProjectLogging'](arg1, arg2);
}

export function LogMessage(arg1, arg2) {
  return window['go']['api']['LoggingService']['LogMessage'](arg1, arg2);
}

export function SetLogLevel(arg1, arg2) {
  return window['go']['api']['LoggingService']['SetLogLevel'](arg1, arg2);
}

export function UpdateLoggingConfig(arg1, arg2) {
  return window['go']['api']['LoggingService']['UpdateLoggingConfig'](arg1, arg2);
}
