// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogHealth() {
  return window['go']['api']['LoggingService']['GetLogHealth']();
}

export function GetLogLevels() {
  return window['go']['api']['LoggingService']['GetLogLevels']();
}

export function GetLoggingConfig() {
  return window['go']['api']['LoggingService']['GetLoggingConfig']();
}

export function GetRecentLogs(arg1) {
  return window['go']['api']['LoggingService']['GetRecentLogs'](arg1);
}

export function InitializeProjectLogging(arg1) {
  return window['go']['api']['LoggingService']['InitializeProjectLogging'](arg1);
}

export function LogMessage(arg1) {
  return window['go']['api']['LoggingService']['LogMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['LoggingService']['SetContext'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['api']['LoggingService']['SetLogLevel'](arg1);
}

export function UpdateLoggingConfig(arg1) {
  return window['go']['api']['LoggingService']['UpdateLoggingConfig'](arg1);
}
