// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {errors} from '../models';
import {api} from '../models';
import {context} from '../models';

export function GetLogHealth():Promise<Record<string, any>|errors.Envelope>;

export function GetLogLevels():Promise<Array<string>|errors.Envelope>;

export function GetLoggingConfig():Promise<api.LoggingConfig|errors.Envelope>;

export function GetRecentLogs(arg1:number):Promise<Array<Record<string, any>>|errors.Envelope>;

export function InitializeProjectLogging(arg1:string):Promise<errors.Envelope>;

export function LogMessage(arg1:api.LogEntry):Promise<errors.Envelope>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetLogLevel(arg1:string):Promise<errors.Envelope>;

export function UpdateLoggingConfig(arg1:Record<string, any>):Promise<errors.Envelope>;
