// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';
import {api} from '../models';

export function GetLogHealth(arg1:context.Context):Promise<Record<string, any>|errors.Envelope>;

export function GetLogLevels(arg1:context.Context):Promise<Array<string>|errors.Envelope>;

export function GetLoggingConfig(arg1:context.Context):Promise<api.LoggingConfig|errors.Envelope>;

export function GetRecentLogs(arg1:context.Context,arg2:number):Promise<Array<Record<string, any>>|errors.Envelope>;

export function InitializeProjectLogging(arg1:context.Context,arg2:string):Promise<errors.Envelope>;

export function LogMessage(arg1:context.Context,arg2:api.LogEntry):Promise<errors.Envelope>;

export function SetLogLevel(arg1:context.Context,arg2:string):Promise<errors.Envelope>;

export function UpdateLoggingConfig(arg1:context.Context,arg2:Record<string, any>):Promise<errors.Envelope>;
