// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';

export function ThreeWay(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<any|errors.Envelope>;
