// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {errors} from '../models';
import {context} from '../models';

export function CreateNode(arg1:types.CreateNodeRequest):Promise<types.Node|errors.Envelope>;

export function DeleteNode(arg1:string):Promise<errors.Envelope>;

export function DeleteProperty(arg1:string,arg2:string):Promise<errors.Envelope>;

export function GetNode(arg1:string):Promise<types.Node|errors.Envelope>;

export function GetNodePath(arg1:string):Promise<Array<types.Node>|errors.Envelope>;

export function GetRootNode():Promise<types.Node|errors.Envelope>;

export function ListChildren(arg1:string):Promise<Array<types.Node>|errors.Envelope>;

export function MoveNode(arg1:types.MoveNodeRequest):Promise<errors.Envelope>;

export function ReorderChildren(arg1:types.ReorderChildrenRequest):Promise<errors.Envelope>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetProperty(arg1:string,arg2:string,arg3:any,arg4:string):Promise<errors.Envelope>;

export function UpdateNode(arg1:types.UpdateNodeRequest):Promise<types.Node|errors.Envelope>;
