// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';
import {errors} from '../models';

export function CreateNode(arg1:context.Context,arg2:types.CreateNodeRequest):Promise<types.Node|errors.Envelope>;

export function DeleteNode(arg1:context.Context,arg2:string):Promise<errors.Envelope>;

export function DeleteProperty(arg1:context.Context,arg2:string,arg3:string):Promise<errors.Envelope>;

export function GetNode(arg1:context.Context,arg2:string):Promise<types.Node|errors.Envelope>;

export function GetNodePath(arg1:context.Context,arg2:string):Promise<Array<types.Node>|errors.Envelope>;

export function GetRootNode(arg1:context.Context):Promise<types.Node|errors.Envelope>;

export function ListChildren(arg1:context.Context,arg2:string):Promise<Array<types.Node>|errors.Envelope>;

export function MoveNode(arg1:context.Context,arg2:types.MoveNodeRequest):Promise<errors.Envelope>;

export function ReorderChildren(arg1:context.Context,arg2:types.ReorderChildrenRequest):Promise<errors.Envelope>;

export function SetProperty(arg1:context.Context,arg2:string,arg3:string,arg4:any,arg5:string):Promise<errors.Envelope>;

export function UpdateNode(arg1:context.Context,arg2:types.UpdateNodeRequest):Promise<types.Node|errors.Envelope>;
