// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNode(arg1) {
  return window['go']['api']['NodeService']['CreateNode'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['api']['NodeService']['DeleteNode'](arg1);
}

export function DeleteProperty(arg1, arg2) {
  return window['go']['api']['NodeService']['DeleteProperty'](arg1, arg2);
}

export function GetNode(arg1) {
  return window['go']['api']['NodeService']['GetNode'](arg1);
}

export function GetNodePath(arg1) {
  return window['go']['api']['NodeService']['GetNodePath'](arg1);
}

export function GetRootNode() {
  return window['go']['api']['NodeService']['GetRootNode']();
}

export function ListChildren(arg1) {
  return window['go']['api']['NodeService']['ListChildren'](arg1);
}

export function MoveNode(arg1) {
  return window['go']['api']['NodeService']['MoveNode'](arg1);
}

export function ReorderChildren(arg1) {
  return window['go']['api']['NodeService']['ReorderChildren'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['NodeService']['SetContext'](arg1);
}

export function SetProperty(arg1, arg2, arg3, arg4) {
  return window['go']['api']['NodeService']['SetProperty'](arg1, arg2, arg3, arg4);
}

export function UpdateNode(arg1) {
  return window['go']['api']['NodeService']['UpdateNode'](arg1);
}
