// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisablePlugin(arg1, arg2) {
  return window['go']['api']['PluginService']['DisablePlugin'](arg1, arg2);
}

export function EnablePlugin(arg1, arg2) {
  return window['go']['api']['PluginService']['EnablePlugin'](arg1, arg2);
}

export function GetEnabledPlugins(arg1) {
  return window['go']['api']['PluginService']['GetEnabledPlugins'](arg1);
}

export function GetPluginPermissions(arg1, arg2) {
  return window['go']['api']['PluginService']['GetPluginPermissions'](arg1, arg2);
}

export function GetPlugins(arg1) {
  return window['go']['api']['PluginService']['GetPlugins'](arg1);
}

export function GrantPermission(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['PluginService']['GrantPermission'](arg1, arg2, arg3, arg4, arg5);
}

export function InitializePluginSystem(arg1) {
  return window['go']['api']['PluginService']['InitializePluginSystem'](arg1);
}

export function InstallPlugin(arg1, arg2) {
  return window['go']['api']['PluginService']['InstallPlugin'](arg1, arg2);
}

export function PluginApplyMutations(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginApplyMutations'](arg1, arg2, arg3);
}

export function PluginCommit(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginCommit'](arg1, arg2, arg3);
}

export function PluginGetNode(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginGetNode'](arg1, arg2, arg3);
}

export function PluginIndexPut(arg1, arg2, arg3, arg4) {
  return window['go']['api']['PluginService']['PluginIndexPut'](arg1, arg2, arg3, arg4);
}

export function PluginListChildren(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginListChildren'](arg1, arg2, arg3);
}

export function PluginNetRequest(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginNetRequest'](arg1, arg2, arg3);
}

export function PluginQuery(arg1, arg2, arg3, arg4) {
  return window['go']['api']['PluginService']['PluginQuery'](arg1, arg2, arg3, arg4);
}

export function PluginSecretsGet(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginSecretsGet'](arg1, arg2, arg3);
}

export function PluginSecretsList(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginSecretsList'](arg1, arg2, arg3);
}

export function PluginSnapshot(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['PluginSnapshot'](arg1, arg2, arg3);
}

export function RevokePermission(arg1, arg2, arg3) {
  return window['go']['api']['PluginService']['RevokePermission'](arg1, arg2, arg3);
}

export function UninstallPlugin(arg1, arg2) {
  return window['go']['api']['PluginService']['UninstallPlugin'](arg1, arg2);
}

export function ValidatePluginManifest(arg1, arg2) {
  return window['go']['api']['PluginService']['ValidatePluginManifest'](arg1, arg2);
}