// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {errors} from '../models';
import {plugins} from '../models';

export function DisablePlugin(arg1:string,arg2:string):Promise<errors.Envelope>;

export function EnablePlugin(arg1:string,arg2:string):Promise<errors.Envelope>;

export function GetEnabledPlugins(arg1:string):Promise<Array<plugins.PluginInstallation>>;

export function GetPluginPermissions(arg1:string,arg2:string):Promise<Array<plugins.PluginPermissionGrant>>;

export function GetPlugins(arg1:string):Promise<Array<plugins.PluginInstallation>>;

export function GrantPermission(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<errors.Envelope>;

export function InitializePluginSystem(arg1:string):Promise<errors.Envelope>;

export function InstallPlugin(arg1:string,arg2:string):Promise<plugins.PluginInstallation>;

export function PluginApplyMutations(arg1:string,arg2:string,arg3:Array<plugins.Mutation>):Promise<errors.Envelope>;

export function PluginCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PluginGetNode(arg1:string,arg2:string,arg3:string):Promise<plugins.NodeData>;

export function PluginIndexPut(arg1:string,arg2:string,arg3:string,arg4:string):Promise<errors.Envelope>;

export function PluginListChildren(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function PluginNetRequest(arg1:string,arg2:string,arg3:plugins.ProxyRequest):Promise<plugins.ProxyResponse>;

export function PluginQuery(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<plugins.NodeData>>;

export function PluginSecretsGet(arg1:string,arg2:string,arg3:string):Promise<plugins.SecretValue>;

export function PluginSecretsList(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function PluginSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RevokePermission(arg1:string,arg2:string,arg3:string):Promise<errors.Envelope>;

export function UninstallPlugin(arg1:string,arg2:string):Promise<errors.Envelope>;

export function ValidatePluginManifest(arg1:string,arg2:string):Promise<Array<string>>;