// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {errors} from '../models';
import {types} from '../models';
import {store} from '../models';
import {context} from '../models';

export function CloseProject():Promise<errors.Envelope>;

export function CreateProject(arg1:string,arg2:Record<string, any>):Promise<types.Project|errors.Envelope>;

export function GetCurrentProject():Promise<store.ProjectStore|string>;

export function GetCurrentProjectPath():Promise<string|errors.Envelope>;

export function GetProjectInfo():Promise<Record<string, any>|errors.Envelope>;

export function IsProjectOpen():Promise<boolean>;

export function OpenProject(arg1:string):Promise<types.Project|errors.Envelope>;

export function ProjectExists(arg1:string):Promise<boolean|errors.Envelope>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateProjectSettings(arg1:Record<string, any>):Promise<errors.Envelope>;
