// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject() {
  return window['go']['api']['ProjectService']['CloseProject']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['api']['ProjectService']['CreateProject'](arg1, arg2);
}

export function GetCurrentProject() {
  return window['go']['api']['ProjectService']['GetCurrentProject']();
}

export function GetCurrentProjectPath() {
  return window['go']['api']['ProjectService']['GetCurrentProjectPath']();
}

export function GetProjectInfo() {
  return window['go']['api']['ProjectService']['GetProjectInfo']();
}

export function IsProjectOpen() {
  return window['go']['api']['ProjectService']['IsProjectOpen']();
}

export function OpenProject(arg1) {
  return window['go']['api']['ProjectService']['OpenProject'](arg1);
}

export function ProjectExists(arg1) {
  return window['go']['api']['ProjectService']['ProjectExists'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['ProjectService']['SetContext'](arg1);
}

export function UpdateProjectSettings(arg1) {
  return window['go']['api']['ProjectService']['UpdateProjectSettings'](arg1);
}
