// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['api']['ProjectService']['Close'](arg1);
}

export function New(arg1, arg2, arg3) {
  return window['go']['api']['ProjectService']['New'](arg1, arg2, arg3);
}

export function Open(arg1, arg2) {
  return window['go']['api']['ProjectService']['Open'](arg1, arg2);
}
