// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject(arg1) {
  return window['go']['api']['ProjectService']['CloseProject'](arg1);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['api']['ProjectService']['CreateProject'](arg1, arg2, arg3);
}

export function GetCurrentProject() {
  return window['go']['api']['ProjectService']['GetCurrentProject']();
}

export function GetCurrentProjectPath(arg1) {
  return window['go']['api']['ProjectService']['GetCurrentProjectPath'](arg1);
}

export function GetProjectInfo(arg1) {
  return window['go']['api']['ProjectService']['GetProjectInfo'](arg1);
}

export function IsProjectOpen(arg1) {
  return window['go']['api']['ProjectService']['IsProjectOpen'](arg1);
}

export function OpenProject(arg1, arg2) {
  return window['go']['api']['ProjectService']['OpenProject'](arg1, arg2);
}

export function ProjectExists(arg1, arg2) {
  return window['go']['api']['ProjectService']['ProjectExists'](arg1, arg2);
}

export function UpdateProjectSettings(arg1, arg2) {
  return window['go']['api']['ProjectService']['UpdateProjectSettings'](arg1, arg2);
}
