// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';
import {types} from '../models';
import {store} from '../models';

export function CloseProject(arg1:context.Context):Promise<errors.Envelope>;

export function CreateProject(arg1:context.Context,arg2:string,arg3:Record<string, any>):Promise<types.Project|errors.Envelope>;

export function GetCurrentProject():Promise<store.ProjectStore|string>;

export function GetCurrentProjectPath(arg1:context.Context):Promise<string|errors.Envelope>;

export function GetProjectInfo(arg1:context.Context):Promise<Record<string, any>|errors.Envelope>;

export function IsProjectOpen(arg1:context.Context):Promise<boolean>;

export function OpenProject(arg1:context.Context,arg2:string):Promise<types.Project|errors.Envelope>;

export function ProjectExists(arg1:context.Context,arg2:string):Promise<boolean|errors.Envelope>;

export function UpdateProjectSettings(arg1:context.Context,arg2:Record<string, any>):Promise<errors.Envelope>;
