// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';

export function Close(arg1:context.Context):Promise<errors.Envelope>;

export function New(arg1:context.Context,arg2:string,arg3:Record<string, any>):Promise<any|errors.Envelope>;

export function Open(arg1:context.Context,arg2:string):Promise<any|errors.Envelope>;
