// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {errors} from '../models';

export function Create(arg1:context.Context,arg2:string,arg3:string,arg4:Record<string, any>):Promise<any|errors.Envelope>;

export function List(arg1:context.Context):Promise<Array<Record<string, any>>|errors.Envelope>;
